### ISSUE TITLE
Some to-do's

### ISSUE THREAD

**Issue by milla** [milla/syveen.github.io#2]
- [x] Advanced English Exam (Oct.)
- [x] Learn something new
- [x] Buy myself a MBP before 2016 May
